# Generated by Django 3.1.6 on 2021-02-27 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210228_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_distributer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.serviceprovider'),
        ),
    ]
