# Generated by Django 3.1.7 on 2021-02-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210228_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='product_pics'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_picture',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='service_pics'),
        ),
    ]
